version: "3.9"
services:
  mqtt-broker:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  redis:
    image: "redis"
  datacollector:
    build: ./datacollector
    depends_on:
      - mqtt-broker
      - redis