version: "3.9"
services:
  mqtt-broker:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  redis:
    image: "redis"
  datacollector:
    build: ./datacollector
    depends_on:
      - mqtt-broker
      - redis
  api:
    build: ./api
    depends_on:
      - redis
    ports:
      - "5000:5000"
  panel:
    build: ./panel
    ports:
      - "8080:80"