version: "3.9"
services:
  # ---------------------------------------------------------------------------- #
  mqtt-broker:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  # ---------------------------------------------------------------------------- #
  influxdb:
    image: "influxdb:2.0"
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2
    env_file:
      - influx.env
  # ---------------------------------------------------------------------------- #
  telegraf:
    image: "telegraf"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mqtt-broker
      - influxdb
    env_file:
      - influx.env
  # ---------------------------------------------------------------------------- #
  api:
    build: ./api
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - BROKER_URL=mqtt-broker
  # ---------------------------------------------------------------------------- #
  panel:
    build: ./panel
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - api
  # ---------------------------------------------------------------------------- #
  intruder-detection:
    build: ./intruder-detection
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    environment:
      - BROKER_URL=mqtt-broker

volumes:
  influxdb: